name: easy_trip
description: "AI-based trip planner app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_markdown: ^0.6.14
  flutter_dotenv: ^5.0.2
  http: ^0.13.5
  google_maps_flutter: ^2.6.0
  shared_preferences: ^2.2.0
  image_picker: ^1.0.4
  package_info_plus: ^4.1.0
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.8
  lottie: ^2.7.0
  firebase_auth: ^5.5.3
  google_sign_in: ^6.3.0
  firebase_core: ^3.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/lottie/loading.json
    - assets/lottie/Trip.json
    - assets/logo_icon.png
    - assets/logo_text.png


flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo_icon.png"


flutter_native_splash:
  color: "#ffffff"
  image: assets/logo_text.png
  android: true
  ios: false


