// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWRqws7gXMu-wfcQsEjgcyIPrsL0kKCVk',
    appId: '1:145277135423:web:7ed1ffef4c072c7c05e68a',
    messagingSenderId: '145277135423',
    projectId: 'easytrip-2025',
    authDomain: 'easytrip-2025.firebaseapp.com',
    storageBucket: 'easytrip-2025.firebasestorage.app',
    measurementId: 'G-JLK324K47C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh8AU88X7bk10o4PfX-rzSccBW_HltE-0',
    appId: '1:145277135423:android:30eae50b9d4884a505e68a',
    messagingSenderId: '145277135423',
    projectId: 'easytrip-2025',
    storageBucket: 'easytrip-2025.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWRqws7gXMu-wfcQsEjgcyIPrsL0kKCVk',
    appId: '1:145277135423:web:466c4af85a7a73f505e68a',
    messagingSenderId: '145277135423',
    projectId: 'easytrip-2025',
    authDomain: 'easytrip-2025.firebaseapp.com',
    storageBucket: 'easytrip-2025.firebasestorage.app',
    measurementId: 'G-EBM1NH7HFH',
  );
}
